### ISSUE TITLE
[Question] on TypeError: Failed to execute 'postMessage' issue:

### ISSUE THREAD

**Issue by badman-rodriguez** [webpack-contrib/worker-loader#139]
- webpack 3.8.1
- latest worker-loader version

I get this error when trying to use the worker through webpack:

`Uncaught TypeError: Failed to execute 'postMessage' on 'Window': 2 arguments required, but only 1 present.`

I console out what the object is:
```
Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: Window, …}
```

While, outside of webpack loader on a differen project, it works fine and i console out the project and it says:
```
[object DedicatedWorkerGlobalScope]
```

So what am i doing wrong?

Webpack config rules
```
 {
        test: /\.worker\.js$/,
        loader: 'worker-loader'
      },
```

filename: `file.worker.js`

**Comment by HowardOhMyGod** [comment]
I have the same issue.

```
webpack: 4.11.1
worker-loader: 2.0.0
```

**Comment by aleskozina** [comment]
Hey Dude!

I was struggling, too.
But i made it. I always got the same error as you when i used it with typescript.
In the end it was just try and error (for me).

But i want to show you what actually my fault was:

Webpack worker-loader:
```
...
{
  test: /worker\.js$/,
  use: {
    loader: 'worker-loader',
    options: { name: 'worker.js' }
  }
},
...
```
*ucking Regex ;-) I just copy pasted it from the doku and did not realize that the dot before `worker` in `test: /\.worker\.js$/,` was escaped. So i changed it to `/worker\.js$/`. Yes, my loader did never match because my worker file was named `worker.ts` and not `file.worker.ts` as used in the doku.

My second mistake was to add it as a entry point. Well, i'm obviously not a webpack master. But i don't remember when i actually added it to the entry point and forgot about this.
Wrong: 
```
entry: {
  bundle: ['./src/index.ts', './src/worker.ts']
},
```
Correct:
```
entry: {
  bundle: ['./src/index.ts']
},
```

After this two changes i finally made it and the context of the worker's `self` was `DedicatedWorkerGlobalScope`

Versions i used:
Env: 
```
webpack: 4.16
node: 10.6.0
typescript: 2.9.2
```

Here is the code if you want to compare it.
https://github.com/aleskozina/worker-test

Hope i could help you!
kr

**Comment by nishio** [comment]
I made a small sample to work with TypeScript.

https://github.com/nishio/tutorial-webworker-with-react/blob/master/README.md

In your case, `Uncaught TypeError: Failed to execute 'postMessage' on 'Window': 2 arguments required, but only 1 present.` is a false alert. Actually we do not need second argument. So I used `@ts-ignore` to suppress alert. It works.

**Comment by evilebottnawi** [comment]
Answers above, we will improve typescript docs in README
