### ISSUE TITLE
Doesn't seem to honor externals configuration

### ISSUE THREAD

**Issue by ernieturner** [webpack-contrib/worker-loader#89]
I have a project which uses this loader and emits two bundles, a main script and a worker script that should run in a web worker. Both of these scripts include a 3rd party library that deals with doing some crypto operations. These libraries have conditionals in them that deal with the Node crypto library and optionally attempt to run `require('crypto')`. I don't need the `crypto-browserify` plugin included in my builds so I've told webpack to ignore these includes by setting my externals in my config like so:

```
externals: {
   crypto: "crypto",
},
```

This works great for the main script and it only includes the files I expect. However, when the worker.js script gets output, it includes all of the crypto-browserify library, which ends up being a few hundred K of code. I don't quite understand why the `externals` config would work for the main script but not for the web worker script, but I haven't been able to figure out a way for webpack to ignore the `require("crypto")` line that ends up in my web worker.

**Comment by TrySound** [comment]
@ernieturner Externals mean you use global variable. Web workers do not have access to global variables, so you should require that file directly or import with `importScripts` function

**Comment by ernieturner** [comment]
I wasn't exactly trying to import the crypto library into my web worker, I was trying to get webpack to stop polyfilling the crypto stuff from node _into_ my web worker. 

However, I think I figured out that I need to specify the `node` option in my webpack config, like so:

```
node: {
  crypto: "empty"
}
```

**Comment by Obi-Dann** [comment]
I am having the issue with externals while using worker-loader in electron app. In electron, workers can have node integration which allows to just `require` a node module, for example some node specific libraries that can/should not be bundled. Because worker-loader does not support externals, I can't get it working as it should in Electron. 

I think it's possible to extend worker-loader to detect `electron-renderer` webpack target and add `ExternalModulePlugin` with externals from the parent compilation or something like that?

@TrySound should I open a new issue or you can reopen this one?

**Comment by evilebottnawi** [comment]
@Obi-Dann `worker-loader` only for `web`, webpack@5 support workers for web/node/etc out of box, try to use webpack@5
