### ISSUE TITLE
[Bug] incorrect worker file paths

### ISSUE THREAD

**Issue by KimmoTukiainen** [webpack-contrib/worker-loader#96]
I have an app at domain.com/subfolder/ 
I'm doing an inline import of a worker script in one of the files.
import * as MyWorker from "worker-loader!./myWorker";

The resulting file name what the browser is trying to load is:
http://domain.com/subfolder793f4dbaa1493689665f.worker.js

That is missing a trailing slash between the folder and the file name, so the file is not found. I tried figuring out a configuration, which could let me set webpack public path for worker-loader specifically, but couldn't find it yet.

Could you push me into the right direction with this?

**Comment by michael-ciniawsky** [comment]
Please provide your `webpack.comfig.js`  aswell

**Comment by jnields** [comment]
Have you tried adding a trailing slash to your publicPath in the webpack config?

**Comment by KimmoTukiainen** [comment]
Hey sorry for the slow response. There was nothing about worker-loader in webpack.config.js initially. We decided to take another route by not loading the file as inline, but by identifying those worker files with the suffix .worker.js

This configuration in webpack module rules solved the issue for me:

`{
                test: /\.worker\.js$/,
                use: [                    
                    {
                        loader: "worker-loader",
                        options: {
                            name: "/[name].js"
                        }
                    }
                ]
            },`

We of course had to exclude those files from the regular babel processing with this
`test: /^(?!.*worker).+\.js$/,`

**Comment by mbrowne** [comment]
If anyone else encounters this, note that you can specify the public path using the inline syntax:

`import GraphqlWorker from 'worker-loader?publicPath=/!graphql/worker.js';`

I prefer the `worker-loader!` syntax because it makes it clearer that it's a special kind of import.

It would be nice if it were possible to specify default settings for a loader in webpack.config.js (for the publicPath setting in this case) so that the inline syntax would still work without having to specify `publicPath` on every import. But I don't know if webpack has such a feature.

**Comment by 0x53A** [comment]
I just also hit this issue. The workaround/fix is easy, but do you think it would be possible to fix this inside worker-loader?

Everything else in webpack seems to work ok without ``publicPath`` being slash-terminated, and it seems like an easy issue to solve.

**Comment by Pyrolistical** [comment]
yeah also ran into this. why does this loader assume publicPath has a trailing slash
